### ISSUE TITLE
How to connect with own mysql server?

### ISSUE THREAD

**Issue by modInfo** [passbolt/passbolt_docker#108]
My docker-compose.yml

```
version: '2'
services:

  passbolt:
    image: passbolt/passbolt:2.1.0-debian
    tty: true
    environment:
      - APP_FULL_BASE_URL=http:/127.0.0.1
      - DATASOURCES_DEFAULT_HOST=localhost
      - DATASOURCES_DEFAULT_USERNAME=passbolt
      - DATASOURCES_DEFAULT_PASSWORD=29FaKe8PaSsqv4
      - DATASOURCES_DEFAULT_DATABASE=passbolt
      - DATASOURCES_DEFAULT_PORT=3306

      - PASSBOLT_REGISTRATION_PUBLIC=true
    volumes:
      - gpg_volume:/var/www/passbolt/config/gpg
      - images_volume:/var/www/passbolt/webroot/img/public
      - ./scripts/wait-for.sh:/usr/bin/wait-for.sh
    tmpfs:
      - /run
    ports:
      - 8020:80

volumes:
  gpg_volume:
  images_volume:
```
