### ISSUE TITLE
aarch64 (ARM) architecture

### ISSUE THREAD

**Issue by maiwenn** [passbolt/passbolt_docker#135]
Hi

I got a
`standard_init_linux.go:211: exec user process caused "exec format error"`

after

`$ docker run --name passbolt --net passbolt_network \
             -p 443:443 \
             -p 80:80 \
             -e DATASOURCES_DEFAULT_HOST=mariadb \
             -e DATASOURCES_DEFAULT_PASSWORD=<mariadb_password> \
             -e DATASOURCES_DEFAULT_USERNAME=<mariadb_user> \
             -e DATASOURCES_DEFAULT_DATABASE=<mariadb_database> \
             -e APP_FULL_BASE_URL=https://mydomain.com \
             passbolt/passbolt:latest
`

following instructions from https://help.passbolt.com/hosting/install/ce/docker.html

I'm on a ubuntu 19.10 VM
my `uname -a` return 

`Linux lbstudio 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:14:25 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux`

Since, this error seems related to target architecture, is there any aarch64 based image available?

ty

**Comment by dlen** [comment]
Hi @maiwenn ,

At the moment we are not providing any arm specific images, it is a nice feature request though!

**Comment by Trojan295** [comment]
I successfully run passbolt in Docker on an Odroid C2. It was just enough to build the clone the repo and build the image on it:
```
git clone https://github.com/passbolt/passbolt_docker.git
cd passbolt_docker
docker build -t passbolt:master .
docker run ... passbolt:master
```

**Comment by Kompas** [comment]
For Raspberry Pi:

- Create docker-compose.yml
- docker-compose up

Content of docker-compose.yml:
```
version: '3.4'
services:
  db:
    image: linuxserver/mariadb:latest
    env_file:
      - env/mysql.env
    volumes:
      - database_volume:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"

  passbolt:
    build: https://github.com/passbolt/passbolt_docker.git
    tty: true
    depends_on:
      - db
    env_file:
      - env/passbolt.env
    volumes:
      - gpg_volume:/var/www/passbolt/config/gpg
      - images_volume:/var/www/passbolt/webroot/img/public
    tmpfs:
      - /run
    command: ["/usr/bin/wait-for.sh", "-t", "0", "db:3306", "--", "/docker-entrypoint.sh"]
    ports:
      - 80:80
      - 443:443

volumes:
  database_volume:
  gpg_volume:
  images_volume:
```

**Comment by innovara** [comment]
I managed to set it up on a Raspberry Pi 4 running Ubuntu 20.04 (arm64/AArch64) doing the following.

1. Clone repo.
```
git clone https://github.com/passbolt/passbolt_docker.git
```
2. Move to working directory.
```
cd passbolt_docker
```
3. Edit MYSQL_ROOT_PASSWORD and MYSQL_PASSWORD in env/mysql.env.
```
nano env/mysql.env
```
```
MYSQL_ROOT_PASSWORD=l<your_root_password>
MYSQL_DATABASE=passbolt
MYSQL_USER=passbolt
MYSQL_PASSWORD=<your_passbolt_password>
```
4. Edit APP_FULL_BASE_URL (I used a FQDN which I had already created i.e. passbolt.yourdomain.com) and DATASOURCES_DEFAULT_PASSWORD (this is the same as MYSQL_PASSWORD)
 
```
nano env/passbolt.env
```
```
# URL
APP_FULL_BASE_URL=https://<your_FQDN>

# Database settings
DATASOURCES_DEFAULT_HOST=db
DATASOURCES_DEFAULT_USERNAME=passbolt
DATASOURCES_DEFAULT_PASSWORD=<your_passbolt_password>
DATASOURCES_DEFAULT_DATABASE=passbolt
DATASOURCES_DEFAULT_PORT=3306
DATASOURCES_QUOTE_IDENTIFIER=true

# Registration
PASSBOLT_REGISTRATION_PUBLIC=false
```
5. Edit docker-compose.yml to comment or delete the image line under passbolt and add build, context and dockerfile
```
nano docker-compose.yml
```
```
  passbolt:
    #image: passbolt/passbolt:latest-ce
    build:
      context: https://github.com/passbolt/passbolt_docker.git
      dockerfile: debian/Dockerfile
```
Optionally, and possibly not recommended, I also edited the database image to use the latest:

```
    image: mariadb:latest
```
I also had to edit the ports for Passbolt, as I have another instance of nginx using those, and to create a site configuration on this nginx instance to redirect to the Passbolt's FQDN to the docker container using proxy_pass and upstream. I also created the certificate for this FQDN using certbot to be used in this instance of nginx.

This is how docker-compose.yml looked like:

```
version: '3.4'
services:
  db:
    image: mariadb:latest
    env_file:
      - env/mysql.env
    volumes:
      - database_volume:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"

  passbolt:
    #image: passbolt/passbolt:latest-ce
    build:
      context: https://github.com/passbolt/passbolt_docker.git
      dockerfile: debian/Dockerfile
    #Alternatively you can use rootless:
    #image: passbolt/passbolt:latest-ce-non-root
    tty: true
    depends_on:
      - db
    env_file:
      - env/passbolt.env
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - images_volume:/usr/share/php/passbolt/webroot/img/public
    command: ["/usr/bin/wait-for.sh", "-t", "0", "db:3306", "--", "/docker-entrypoint.sh"]
    ports:
    #  - 80:80
    #  - 443:443
   #Custom port configuration
    # 8080 and 4433 are the ports listening on the host
    # 80 and 443 are the ports listening on the container
      - 8080:80
      - 4433:443
    #Alternatively for non-root images:
    # - 80:8080
    # - 443:4433

volumes:
  database_volume:
  gpg_volume:
  images_volume:
```
6. Build the containers.
```
docker-compose -f docker-compose.yml up
```
7. If everything goes well press Ctrl+C and start the containers again in detached mode.
```
docker-compose -f docker-compose.yml up -d
```
8. Create your first admin user.
```
docker exec passbolt su -m -c "bin/cake passbolt register_user -u your@email.com -f yourname -l surname -r admin" -s /bin/sh www-data
```
9. It will return a URL which you have to use on your browser to complete the registration.
