### ISSUE TITLE
php times out and causes 500 errors

### ISSUE THREAD

**Issue by s4ke** [passbolt/passbolt_docker#153]
We are using `3.0.1-ce` from docker hub.

Our database is mariadb  `Ver 15.1 Distrib 10.1.47-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2` on the host

This is on an instance we upgraded from 2.13.5 to 3.0.1:

```
2021/02/26 09:21:57 [error] 154#154: *62 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: _, request: "GET /settings.json?api-version=v2 HTTP/1.0", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock", host: "localhost:8444"
2021/02/26 09:21:57 [error] 154#154: *63 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: _, request: "GET /auth/is-authenticated.json HTTP/1.0", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock", host: "localhost:8444"
```

Also, we get these errors from the apache inside the docker container:

```
2021-02-26 09:22:53,357 INFO reaped unknown pid 216
2021-02-26 09:22:53,364 INFO reaped unknown pid 218
2021-02-26 09:22:53,377 INFO reaped unknown pid 220
2021-02-26 09:22:53,390 INFO reaped unknown pid 222
2021-02-26 09:22:53,396 INFO reaped unknown pid 224
2021-02-26 09:22:53,403 INFO reaped unknown pid 226
2021-02-26 09:22:53,426 INFO reaped unknown pid 228
2021-02-26 09:22:53,451 INFO reaped unknown pid 231
2021-02-26 09:22:53,458 INFO reaped unknown pid 233
2021-02-26 09:22:53,473 INFO reaped unknown pid 235
2021-02-26 09:22:53,486 INFO reaped unknown pid 237
2021-02-26 09:22:53,508 INFO reaped unknown pid 239
2021-02-26 09:22:53,589 INFO reaped unknown pid 242
```

We configure everything via env vars and use the mounts from here:

```
   volumes:
      - "/data/ansible/passbolt/data/gpg:/etc/passbolt/gpg"
      - "/data/ansible/passbolt/data/images:/usr/share/php/passbolt/webroot/img/public"
      - "/data/ansible/certs/{{ passbolt_cert_dir }}:/certs"
      - "/data/ansible/passbolt/mariadb/mariadb.cnf:/etc/mysql/mariadb.conf.d/mariadb.cnf"
    env:
      DATASOURCES_DEFAULT_HOST: "{{ database_server_str }}"
      DATASOURCES_DEFAULT_USERNAME: "{{ passbolt_db_user }}"
      DATASOURCES_DEFAULT_PASSWORD: "{{ passbolt_db_passwd }}"
      DATASOURCES_DEFAULT_DATABASE: "{{ passbolt_db }}"
      APP_FULL_BASE_URL: "https://{{ passbolt_domain }}"
      DATASOURCES_DEFAULT_SSL_KEY: "/certs/server.key"
      DATASOURCES_DEFAULT_SSL_CERT: "/certs/server.crt"
      DATASOURCES_DEFAULT_SSL_CA: "/certs/rootCA.crt"
      SECURITY_SALT: "{{ passbolt_salt }}"
      PASSBOLT_KEY_LENGTH: "{{ passbolt_key_length }}"
      PASSBOLT_SUBKEY_LENGTH: "{{ passbolt_subkey_length }}"
      PASSBOLT_KEY_NAME: "{{ passbolt_default_user }}"
      PASSBOLT_KEY_EMAIL: "{{ passbolt_default_user_mail }}"
      PASSBOLT_KEY_EXPIRATION: "{{ passbolt_key_expiration }}"
      EMAIL_TRANSPORT_DEFAULT_CLASS_NAME: "{{ passbolt_email_transport_class_name }}"
      EMAIL_DEFAULT_FROM: "{{ passbolt_email_from }}"
      EMAIL_DEFAULT_TRANSPORT: "default"
      EMAIL_TRANSPORT_DEFAULT_HOST: "{{ passbolt_email_host }}"
      EMAIL_TRANSPORT_DEFAULT_PORT: "{{ passbolt_email_port }}"
      EMAIL_TRANSPORT_DEFAULT_TIMEOUT: "{{ passbolt_email_timeout }}"
      EMAIL_TRANSPORT_DEFAULT_USERNAME: "{{ passbolt_email_user }}"
      EMAIL_TRANSPORT_DEFAULT_PASSWORD: "{{ passbolt_email_password }}"
      EMAIL_TRANSPORT_DEFAULT_TLS: "{{  passbolt_email_use_tls }}"
      PASSBOLT_EMAIL_SHOW_COMMENT: "false"
      PASSBOLT_EMAIL_SHOW_DESCRIPTION: "false"
      PASSBOLT_EMAIL_SHOW_SECRET: "false"
      PASSBOLT_EMAIL_SHOW_URI: "false"
      PASSBOLT_EMAIL_SHOW_USERNAME: "false"
    restart_policy: unless-stopped
```
