### ISSUE TITLE
Unable to install because of a DB migration issue

### ISSUE THREAD

**Issue by stratoss** [passbolt/passbolt_docker#172]
### Configuration
MySQL 8 (it works fine with MariaDB 10, the issue is with MySQL 8)

docker-compose.yaml
```
services:
  passbolt_new:
    image: passbolt/passbolt:latest-ce
    #Alternatively you can use rootless:
    #image: passbolt/passbolt:latest-ce-non-root
    restart: unless-stopped
    tty: true
    environment:
      APP_FULL_BASE_URL: https://passbolt.local
      DATASOURCES_DEFAULT_HOST: "passbolt_dbhost"
      DATASOURCES_DEFAULT_PORT: "25060"
      DATASOURCES_DEFAULT_USERNAME: "passbolt_user"
      DATASOURCES_DEFAULT_PASSWORD: "passbolt_pass"
      DATASOURCES_DEFAULT_DATABASE: "passbolt_db"
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    command: /docker-entrypoint.sh
    ports:
      - 80:80
      - 443:443
    #Alternatively for non-root images:
    # - 80:8080
    # - 443:4433

volumes:
  gpg_volume:
  jwt_volume:
```

### What you did :memo:
executed `docker-compose up`

### What happened :collision: :clipboard:
passbolt_new_1  | Running baseline checks, please wait...
passbolt_new_1  | Critical healthchecks are OK
passbolt_new_1  | Cleaning up existing tables if any.
passbolt_new_1  | -------------------------------------------------------------------------------
passbolt_new_1  | 0 tables dropped
passbolt_new_1  | Install the schema and default data.
passbolt_new_1  | -------------------------------------------------------------------------------
passbolt_new_1  | using migration paths 
passbolt_new_1  |  - /etc/passbolt/Migrations
passbolt_new_1  | using seed paths 
passbolt_new_1  |  - /etc/passbolt/Seeds
passbolt_new_1  | using environment default
passbolt_new_1  | using adapter mysql
passbolt_new_1  | using database passbolt
passbolt_new_1  | ordering by creation time
passbolt_new_1  | 
passbolt_new_1  |  == 20170830064410 V162InitialMigration: migrating
passbolt_new_1  | PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'passbolt' in 'where clause' in /usr/share/php/passbolt/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php:39
passbolt_new_1  | Stack trace:

### What you expected to happen
The migration to pass
