### ISSUE TITLE
Memory leak in GPG agent

### ISSUE THREAD

**Issue by hikariatama** [passbolt/passbolt_docker#207]
Memory usage before and after restart:
![image](https://github.com/passbolt/passbolt_docker/assets/36935426/aa0c2e53-1b4a-4903-97ef-56bc9c74c23a)
Installed on Docker
If you need any further info, please request.

**Comment by dlen** [comment]
Hi @hikariatama 

This memory usage is quite weird, also the graph doesn't show any units. Are these GB of memory used?
How are you running passbolt? Using docker-compose? If so, could you provide the docker-compose.yaml? Also when you restarted can you confirm that you just restarted passbolt container and no other containers like mysql?

**Comment by hikariatama** [comment]
> the graph doesn't show any units
it indeed doesn't. I don't have a specific feature to view the mem usage of each process independently. Green one is some qemu process of passbolt

> Are these GB of memory used?
yer

> How are you running passbolt? Using docker-compose? If so, could you provide the docker-compose.yaml? 

```yaml
version: '3.9'
services:
  db:
    image: mariadb:10.3
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "passbolt"
      MYSQL_USER: "passbolt"
      MYSQL_PASSWORD: "<pass>"
    volumes:
      - database_volume:/var/lib/mysql

  passbolt:
    image: passbolt/passbolt:latest-ce
    #Alternatively you can use rootless:
    #image: passbolt/passbolt:latest-ce-non-root
    restart: unless-stopped
    depends_on:
      - db
    environment:
      APP_FULL_BASE_URL: <url>
      DATASOURCES_DEFAULT_HOST: "db"
      DATASOURCES_DEFAULT_USERNAME: "passbolt"
      DATASOURCES_DEFAULT_PASSWORD: "<pass>"
      DATASOURCES_DEFAULT_DATABASE: "passbolt"
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    command: ["/usr/bin/wait-for.sh", "-t", "0", "db:3306", "--", "/docker-entrypoint.sh"]
    ports:
      # - 80:80
      # - 443:443
      # Linked directly to docker network IP
    #Alternatively for non-root images:
      - 1128:80
      - 1129:433

volumes:
  database_volume:
  gpg_volume:
  jwt_volume:
```

> Also when you restarted can you confirm that you just restarted passbolt container and no other containers like mysql?
You have to just trust me on that. I restarted passbolt stack using Portainer
