### ISSUE TITLE
Error: wait-for.sh: waiting for passbolt_db:3366 without a timeout

### ISSUE THREAD

**Issue by ZahiriNatZuke** [passbolt/passbolt_docker#226]
this is my docker-compose.yml file:

```yml                                                                                        
version: "3.9"
services:
  passbolt_db:
    image: bitnami/mariadb
    restart: unless-stopped
    container_name: passbolt_db
    environment:
      MARIADB_DATABASE: "passbolt"
      MARIADB_USER: "zahirinatzuke"
      MARIADB_ROOT_PASSWORD: "<password>"
      MARIADB_PASSWORD: "<password>"
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - 3366:3306

  passbolt:
    #image: passbolt/passbolt:latest-ce
    #Alternatively you can use rootless:
    image: passbolt/passbolt:latest-ce-non-root
    restart: unless-stopped
    container_name: passbolt
    depends_on:
      - passbolt_db
    environment:
      APP_FULL_BASE_URL: https://some.domain
      DATASOURCES_DEFAULT_HOST: "passbolt_db"
      DATASOURCES_DEFAULT_USERNAME: "zahirinatzuke"
      DATASOURCES_DEFAULT_PASSWORD: "<password>"
      DATASOURCES_DEFAULT_DATABASE: "passbolt"
    volumes:
      - ./gpg_data:/etc/passbolt/gpg
      - ./jwt_data:/etc/passbolt/jwt
    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "passbolt_db:3366",
        "--",
        "/docker-entrypoint.sh",
      ]
    ports:
      - 82:8080
      - 444:4433
    #Alternatively for non-root images:
    # - 80:8080
    # - 443:4433
```

When I check the logs of the passbolt container, I always get the same log:
```cmd
docker logs passbolt
wait-for.sh: waiting for passbolt_db:3366 without a timeout
```
