### ISSUE TITLE
sed error on first boot

### ISSUE THREAD

**Issue by NotSqrt** [passbolt/passbolt_docker#41]
Hi,

The setup seems to fail with :
`sed: -e expression #1, char 20: unknown option to `s'`

I've no particular context to help track down the error, but I can spend some time on it if needed !

Thanks.

**Comment by dlen** [comment]
Hi @NotSqrt thanks for your interest in passbolt! Could you describe which version of the image are you using and the command to launch the container? That would help

**Comment by NotSqrt** [comment]
Hi,

I tried to write a docker-compose.yml, as follows:
```yaml
version: '2'

services:
  db:
    container_name: passbolt_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: c0mplexp4ss
      MYSQL_DATABASE: passbolt
      MYSQL_USER: passbolt
      MYSQL_PASSWORD: P4ssb0lt

  passbolt:
    container_name: passbolt_web
    image: passbolt/passbolt:1.6.1-alpine
    depends_on:
      - db
    ports:
      - "80"
      - "443"
    environment:
      db_host: db:3306
```

And running :
`docker-compose up passbolt_db`, wait for the db setup to finish, then `docker-compose up passbolt_web` in another shell.
