### ISSUE TITLE
Defining DB_HOST as string causes installation crash

### ISSUE THREAD

**Issue by elboletaire** [passbolt/passbolt_docker#60]
I'm deploying bolt using a `docker-compose.yml` file, and in that file I've named the database container as `db`.

After that I linked passbolt using `links` option, and setting `DB_HOST` as `db`:

<details><summary>

`docker-compose.yml` contents:

</summary>

~~~yaml
db:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: whatever
    MYSQL_DATABASE: passbolt
    MYSQL_USER: passbolt
    MYSQL_PASSWORD: P4ssb0lt

passbolt:
  image: passbolt/passbolt:latest 
  links:
  - db
  environment:
    DB_HOST: db
    EMAIL_FROM: ourmail@cirici.com
    EMAIL_HOST: smtp.gmail.com
    EMAIL_USERNAME: ourmail@cirici.com
    EMAIL_PASSWORD: ourmailpassword
    EMAIL_TLS: 'true'
    KEY_LENGTH: 4096
    SUBKEY_LENGTH: 2048
    KEY_NAME: Cirici New Media
    # [...] Other vars which are not important for the issue
~~~

</details>

Using this configuration crashes with the following error:

Unless I specify `DB_PORT: 3306` (which is, following the docs, the default value..):

    passbolt_1  | Unknown suffix 't' used for variable 'port' (value 'tcp://172.17.0.22:3306')
    passbolt_1  | mysql: Error while setting value 'tcp://172.17.0.22:3306' to 'port'****

Setting `DB_PORT` to 3306 fixes this issue (but a new one rises, I'm creating an issue for it..).

**Comment by dlen** [comment]
Hi @elboletaire, thanks for your interest in passbolt!
Seems like the environment variables are not correctly defined, docker-compose env variables should be defined as:

```environment:
       - DB_HOST=db
       - EMAIL_FROM=...
....
```
Could you please check that? Also take a look on this that might help you: https://github.com/dlen/passbolt-compose

**Comment by elboletaire** [comment]
This is a yaml file. Array lists can be defined either:

~~~yaml
list:
- WHATEVER=value
- ANOTHERKEY=value
~~~

Or...

~~~yaml
list:
  WHATEVER: value
  ANOTHERKEY: value
~~~

**Comment by elboletaire** [comment]
The issue is, defining only `DB_HOST` does not work, whilst defining both `DB_HOST` and `DB_PORT` (this last one to its default value), works.

**Comment by elboletaire** [comment]
> Could you please check that? Also take a look on this that might help you: https://github.com/dlen/passbolt-compose

That `docker-compose.yml` does not even validate...

~~~
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
~~~

**Comment by dlen** [comment]
Yes, you are right on the yaml syntax. I commented it out syntax errors upfront, however the problem relies on the docker-compose.yaml.
I was able to reproduce your problem. Taking a closer look, the fact that you are using the `links` instruction and you are not defining the docker-compose version leads to docker-compose to fallback to version 1 of docker-compose and automatically declare [a set of environment variables that start with the name of the container](https://docs.docker.com/compose/link-env-deprecated/) which are deprecated on recent versions of docker-compose. Unfortunately using `db` as the name of the service you want to link to creates a `DB_PORT` env variable with the following content: `'tcp://172.17.0.22:3306'` which is incorrect and forces the docker-entrypoint to crash.

I don't know if you are defining the docker-compose version on your yaml file and this wasn't reflected on your yaml snippet but I encourage you to do it. Also, create a services section instead of declaring your containers on the root of the yaml file plus use depends_on instead of links since there is no need to use it for container networking purposes. Moreover depends_on sets dependency on starting containers as links used to do.

If you don't feel like to upgrade your composer file a possible workaround is, as you suggested, define the `DB_PORT` in your composer file.

Hope this helps!

**Comment by elboletaire** [comment]
mmm.... nope. I'm currently using version two and the issue's still there. If I don't specify `DB_PORT` passbolt crashes with the error `Unknown suffix 't'...`:

![imatge](https://user-images.githubusercontent.com/153305/30077577-92376f4c-927c-11e7-84ad-75e8bd3a4713.png)

Here's my current `docker-compose` file, just in case there are doubts about it:

~~~yaml
version: '2'

services:
  db:
    image: mariadb:5.5
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: whatever
      MYSQL_DATABASE: passbolt
      MYSQL_USER: passbolt
      MYSQL_PASSWORD: P4ssb0lt

  passbolt:
    image: passbolt/passbolt:latest
    links:
    - db
    depends_on:
    - db
    network_mode: bridge
    environment:
      DB_HOST: db
      # Commented to demonstrate that it crashes. Uncomment it to make it work.
      # DB_PORT: 3306
      EMAIL_FROM: ourmail@cirici.com
      EMAIL_HOST: smtp.gmail.com
      EMAIL_USERNAME: ourmail@cirici.com
      EMAIL_PASSWORD: ourmailpassword
      EMAIL_TLS: 'true'
      KEY_LENGTH: 4096
      SUBKEY_LENGTH: 2048
      KEY_NAME: Cirici New Media
      # [...] Other vars which are not important for the issue
~~~

This issue should be reopened.

**Comment by dlen** [comment]
Hi @elboletaire as I stated on my previous comment and on the link to the docker compose doc I attached on the very same comment, the problem is the usage of the `links` section. 
If you want to continue using `links` section you should rename the `db` service to something else since the usage of `links` injects environment variables on the passbolt container to allow networking with the db container that conflict with the passbolt docker-entrypoint ones. A valid composer file would be:

```
version: '2'

services:
  db_passbolt:
    image: mariadb:5.5
    environment:
      MYSQL_ROOT_PASSWORD: whatever
      MYSQL_DATABASE: passbolt
      MYSQL_USER: passbolt
      MYSQL_PASSWORD: P4ssb0lt

  passbolt:
    image: passbolt/passbolt:latest
    links:
      - db_passbolt
    environment:
      DB_HOST: db_passbolt
      # Commented to demonstrate that it crashes. Uncomment it to make it work.
      # DB_PORT: 3306
      EMAIL_FROM: ourmail@cirici.com
      EMAIL_HOST: smtp.gmail.com
      EMAIL_USERNAME: ourmail@cirici.com
      EMAIL_PASSWORD: ourmailpassword
      EMAIL_TLS: 'true'
      KEY_LENGTH: 4096
      SUBKEY_LENGTH: 2048
      KEY_NAME: Cirici New Media
```

If you rather to keep using `db` as the name of the database container service you should use `depends_on` rather than links, which is IMHO a better practice:

```
version: '2'

services:
  db:
    image: mariadb:5.5
    environment:
      MYSQL_ROOT_PASSWORD: whatever
      MYSQL_DATABASE: passbolt
      MYSQL_USER: passbolt
      MYSQL_PASSWORD: P4ssb0lt

  passbolt:
    image: passbolt/passbolt:latest
    depends_on:
      - db
    environment:
      DB_HOST: db
      # Commented to demonstrate that it crashes. Uncomment it to make it work.
      # DB_PORT: 3306
      EMAIL_FROM: ourmail@cirici.com
      EMAIL_HOST: smtp.gmail.com
      EMAIL_USERNAME: ourmail@cirici.com
      EMAIL_PASSWORD: ourmailpassword
      EMAIL_TLS: 'true'
      KEY_LENGTH: 4096
      SUBKEY_LENGTH: 2048
      KEY_NAME: Cirici New Media
```
Hope this helps.
